config/routes.rb
Rails.application.routes.draw do  
  devise_for :users
  root to: 'homes#index'
  resources :users, only: [:edit, :update, :show]
  resources :tweets
  resources :calendars
  resources :rooms, only: [:index, :new, :create, :destroy] do
  resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
 belongs_to :user
  
  with_options presence: true do
      validates :title
      validates :start_time
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :content, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  has_many :messages, dependent: :destroy

  validates :subject, presence: true
  
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  with_options presence: true do
    validates :content
    validates :hotel_name
    validates :image 
 end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  devise :authentication_keys => [:employee_id_number]  

  has_many :tweets
  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
  has_many :calendars

  with_options presence: true do
   validates :employee_id_number,
    length: { maximum: 5 },
    format: { with: /\A\d{,5}\z/ }

   validates :name,
   format: { with: /\A[ぁ-んァ-ン一-龥]/, message: '全角で登録してください' } 
   validates :name_kana,
   format: { with: /\A[ァ-ヶー－]+\z/, message: '全角カナで登録してください' } 
   
   validates :email
   validates :password,
   format: { with: /\A(?=.*?[a-zA-Z])(?=.*?\d)[a-zA-Z\d]{6,}\z/, message: '英数字混合6文字以上で登録してください' },
   on: :create

   
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name, :name_kana])
    end
  end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController

  def index
    @calendars = current_user.calendars
  end

  def new
    @calendar = current_user.calendars.new
  end

  def show
    @calendar = current_user.calendars.find(params[:id])
  end

  def edit
    @calendar = current_user.calendars.find(params[:id])
  end

  def update
    @calendar= current_user.calendars.find(params[:id])
    @calendar.update(calendar_params)
    redirect_to calendars_path
  end

  def create
    @calendar = current_user.calendars.new(calendar_params)
    if @calendar.save
      redirect_to action: :index
    else
      redirect_to new_calendar_path
    end
  end

  def destroy
    @calendar = current_user.calendars.find(params[:id])
    @calendar.destroy
    redirect_to calendars_path
  end


  private
  def calendar_params
    params.require(:calendar).permit(:start_time, :title, :content).merge(user_id: current_user.id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = Message.new
    @room = Room.find(params[:room_id])
    @messages = @room.messages.includes(:user).order("created_at DESC")
  end

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if @message.save
      redirect_to room_messages_path(@room)
    else
      @messages = @room.messages.includes(:user)
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content).merge(user_id: current_user.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def index
    @rooms = Room.includes(:user).order("created_at DESC")
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to action: :index
  end

  private
  def room_params
    params.require(:room).permit(:subject, user_ids:[])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:edit, :show, :destroy, :update]
  before_action :move_to_index,  only: [:edit, :update, :destroy]
 
  def index
    @tweets = Tweet.includes(:user).order("created_at DESC")
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.valid?  
       @tweet.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def destroy
    @tweet.destroy
    redirect_to action: :index
  end

  def edit
  end

  def update
    @tweet.update(tweet_params)
    redirect_to action: :index
  end

  def show
  end


  private
  def tweet_params
    params.require(:tweet).permit(:hotel_name, :content, :image).merge(user_id: current_user.id)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index if current_user.id != @tweet.user_id 
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @name = user.name
    @tweets = user.tweets
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calendars/edit.html.erb
<%= form_with(model: @calendar, local: true) do |form| %>

  <div class="title">
    <%= form.label :タイトル %>
    <%= form.text_field :title %>
  </div>

    <div class="time">
    <%= form.label :開始時間 %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="content">
    <%= form.label :詳細 %>
    <%= form.text_field :content %>
  </div>


  <div class="submit">
    <%= form.submit %>
  </div>

<% end %>

app/views/calendars/index.html.erb
<div class= 'calender'>
 <a href="/">TOPに戻る</a>|
 <%= link_to '予定を入力', new_calendar_path %>
 <%= month_calendar events: @calendars do |date, calendars| %>
 <%= date.day %>
 <% calendars.each do |calender| %>
  <div>
 <%= link_to calender.title,calender %>
  </div> 
   <% end %>
 <% end %>
</div>

app/views/calendars/new.html.erb
<%= form_with(model: @calendar, local: true) do |form| %>

  <div class="title">
    <%= form.label :タイトル %>
    <%= form.text_field :title %>
  </div>

    <div class="time">
    <%= form.label :開始時間 %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="content">
    <%= form.label :詳細 %>
    <%= form.text_field :content %>
  </div>


  <div class="submit">
    <%= form.submit %>
  </div>

<% end %>

app/views/calendars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>タイトル</strong>
  <%= @calendar.title %>
</p>

<p>
  <strong>時間</strong>
  <%= @calendar.start_time.strftime("%Y-%m-%d %H:%M") %>
</p>

<p>
  <strong>内容</strong>
  <%= @calendar.content %>
</p>

<%= link_to '編集', edit_calendar_path(@calendar) %> |
<%= link_to '削除', calendar_path(@calendar.id), method: :delete %> |
<%= link_to '戻る', calendars_path %>

app/views/homes/index.html.erb
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="homes.scss">

    <title>営業職員用アプリ</title>
  </head>
  <body>

    <!-- ナビゲーションバー -->
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #AEFFBD;">
   <div class="container-fluid">
   <a class="navbar-brand" href="#">営業職員用アプリ</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
    </button> 
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to "新着情報", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "スケジュール管理", calendars_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "宿泊施設口コミ", tweets_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "チャット", rooms_path, class: "nav-link" %>
        </li>
      </ul>
    
    <ul class='nav-right'>
       <% if user_signed_in? %>
      <li><%= link_to current_user.name, root_path, class: "user-name" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% end %>
       </ul>
     </div>
    </nav>
 

    <!-- image -->
    <img src="/assets/office.jpg" class="img-fluid" alt="トップ画像">




    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
    <%= @room.subject %>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
    <%= link_to "チャットを削除する", room_path(@room), method: :delete %>
    </div>
  </div>
</div>

 <div class="messages">
  <%= render partial: 'message', collection: @messages %>
 </div>
 <%= form_with model: [@room, @message], class: 'form', local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
  <% end %> 
</div>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <!-- 投稿したユーザー名情報を出力する -->
      <%= message.user.name %>
    </div>
    <div class="message-date">
      <!-- 投稿した時刻を出力する -->
      <%= l message.created_at %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <!-- 投稿したメッセージ内容を記述する -->
      <%= message.content %>
    </div>
  </div>
</div>

app/views/messages/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
<a href="/">TOPに戻る</a>|
  </div>
  <div class="create-room">
   <%= link_to "チャット作成", new_room_path %>
  </div>
</div>

<div class="rooms">
  <% current_user.rooms.each do |room| %>
    <div class="room">
      <div class="room-name">
    <%= link_to room.subject, room_messages_path(room) %>
      </div>
    </div>
  <% end %>
</div>

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="side-bar">
  <%= render "messages/side_bar" %>
  </div>
  <div class="chat">
    <%= render "main_chat" %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "messages/side_bar" %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%= form_with model: @room, local: true do |f| %>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :件名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :subject, class: 'chat__room_name chat-room-form__input', placeholder: '件名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
        <select name="room[user_ids][]">
          <option value="">チャットするユーザーを選択してください</option>
          <% User.where.not(id: current_user.id).each do |user| %>
              <option value=<%= user.id %>><%= user.name %></option>
          <% end %>
        </select>
        <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
     </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>  
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/tweets/edit.html.erb
<div class="contents row">
  <div class="container">
    <h2>編集する</h2>
    <%= form_with model: @tweet, local: true do |f| %>
      <%= render 'devise/shared/error_messages', model: f.object %>
        宿泊施設名<span class="indispensable">必須</span>
      <%= f.text_field :hotel_name, placeholder: "ホテル/旅館など" %>
        クチコミ<span class="indispensable">必須</span>
      <%= f.text_area :content, placeholder: "宿泊した感想など", rows: "20" %>
        写真<span class="indispensable">必須</span>
       <%= f.file_field :image, id:"tweet-image", placeholder: "最高の1枚を！"  %>
      
      <!-- 変更ボタン-->
      <div class="change-btn-contents">
      <%= f.submit "更新する", class:"change-btn" %>
      <%=link_to 'もどる', tweets_path, class:"back-btn" %>

       </div>
    </div>
    <% end %>
  </div>  

app/views/tweets/index.html.erb
<header class="header">
  <h4><a href="/"> TOPに戻る</a></h4>
  <%= link_to "マイページ", "/users/#{current_user.id}", class: "balloon1" %>
  <%= link_to "投稿する", new_tweet_path, class: "balloon2" %>
</header>
<h1 class="tweets-title">口コミ情報</h1>
<% @tweets.each do |tweet| %>
    <a href="/users/<%= tweet.user.id %>">
     <p>投稿者：<%= tweet.user.name %></p></a>
     <p>宿泊施設：<%= tweet.hotel_name %><p>
     <p>コメント：<%= tweet.content %> </p>

<%= link_to tweet_path(tweet.id) do %> 
<%= image_tag tweet.image.variant(resize: '900x900'), class: "tweet-img" if tweet.image.attached? %>
  <% end %>
 <% end %>

app/views/tweets/new.html.erb
<div class="contents row">
  <div class="container">
   <h2>投稿する</h2>
    <%= form_with model: @tweet, local: true do |f| %>
    <%= render 'devise/shared/error_messages', model: f.object %>
       <span class="indispensable">必須</span>
      <%= f.label :宿泊施設名%>
      <%= f.text_field :hotel_name, placeholder: "ホテル/旅館など" %>
      　<span class="indispensable">必須</span>
      <%= f.label :口コミ%>
      <%= f.text_area :content, placeholder: "宿泊した感想など", rows: "20" %>
      　<span class="indispensable">必須</span>
       <%= f.label :写真 %>
       <%= f.file_field :image, id:"tweet-image" %>
      <%= f.submit "SEND" %>
      <%=link_to 'もどる', tweets_path, class:"back-btn" %>
    <% end %>
  </div>
</div> 

app/views/tweets/show.html.erb
      <% if current_user.id == @tweet.user_id %>
          <%= link_to "口コミの編集", edit_tweet_path(@tweet.id), method: :get %>｜
          <%= link_to "削除", tweet_path(@tweet.id) , method: :delete %>
      <% end %>

    <p><%= @tweet.hotel_name%></p>
    <p><%= image_tag @tweet.image.variant(resize: '700x700'),class: "tweet-img" %></p>
      <a href="/users/<%= @tweet.user.id %>"> </a>
     <p>投稿者：<%= @tweet.user.name %></p>
  

app/views/users/show.html.erb
<%= render "devise/shared/header"%>

<div class="contents-row">
<%=link_to '口コミに戻る', tweets_path, class:"back-btn" %>
  <p><%= @name %>さんの投稿一覧</p>
  <% @tweets.each do |tweet| %>
    <%= image_tag tweet.image.variant(resize: '900x900') %>
       <p>宿泊施設：<%= tweet.hotel_name %></p>
       <p>コメント：<%= tweet.content %></p>
  <% end %>
</div>